### ISSUE TITLE
Hapi quickstart seed project download does not fill in Auth0 API Keys.

### ISSUE THREAD

**Issue by jgelsey** [auth0/docs#1692] opened 2016-06-30 21:01 UTC
https://auth0.com/docs/quickstart/backend/hapi#1-add-hapi-auth-jwt-dependency

**Comment by mpaktiti** [comment] 2016-08-31 10:23
https://techaid.atlassian.net/browse/AUTH-3261

**Comment by mpaktiti** [comment] 2016-08-31 10:52
Assigned to TechAid.

**Comment by iannyanes** [comment] 2016-09-04 19:36
The keys needed for the API to work are on the .env file which is filled when the user downloads the sample when logged in. Is there any other keys we are not checking @mpaktiti @jgelsey ? If so, please provide more information to reproduce and fix the issue.

**Comment by mpaktiti** [comment] 2016-09-05 08:30
Confirmed it works for me as well.

@jgelsey I will close this issue since we cannot reproduce but if it does not work for you still let me know.

**Closed as completed by mpaktiti** 2016-09-05 08:30 UTC
Labels: bug, quickstart
