### ISSUE TITLE
invalid_response on download seed project

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#4774] opened 2017-08-04 10:47 UTC
(AUTH-4180)
I've tried to download ASP.NET Core Web API v2 seed project and got invalid_response instead:
![image](https://user-images.githubusercontent.com/1114365/28965280-effb989c-7918-11e7-9301-0c0139828d09.png)

**Comment by mpaktiti** [comment] 2017-08-11 08:09
Quickstart that throws this error https://auth0.com/docs/quickstart/backend/aspnet-core-webapi/v2/01-authorization

Same error for this one https://auth0.com/docs/quickstart/webapp/aspnet-core/v2/01-login  so I'm thinking that it might have to do with the `branch` metadata

**Comment by davidpatrick** [comment] 2017-08-22 01:37
@mpaktiti The problem is coming from how github formats the branch name in the gzip file.  If the branch is named with `v#` it will omit the v inside of the zip entries headers.   For instance, the packager is looking for `auth0-aspnetcore-webapi-samples-v2/quickstart/01-authorization/` but the header information is formatted as `auth0-aspnetcore-webapi-samples-2/quickstart/01-authorization/`.

There is an open pull request to fix this issue

**Comment by mpaktiti** [comment] 2017-08-24 13:07
Fixed by @davidpatrick 💯

**Closed as completed by mpaktiti** 2017-08-24 13:07 UTC
