### ISSUE TITLE
Pages Without Meta Description

### ISSUE THREAD

**Issue by plaurino** [auth0/docs#364] opened 2015-09-07 17:32 UTC
https://auth0.com/docs
https://auth0.com/docs/connections/enterprise/google-apps
https://auth0.com/docs/connections/enterprise/samlp
https://auth0.com/docs/connections/social/evernote-sandbox
https://auth0.com/docs/connections/social/salesforce-community
https://auth0.com/docs/connections/social/salesforce-sandbox
https://auth0.com/docs/connections/social/thecity-sandbox
https://auth0.com/docs/connections/social/yammer
https://auth0.com/docs/quickstart/native-mobile
https://auth0.com/docs/quickstart/native-mobile/android
https://auth0.com/docs/quickstart/native-mobile/cordova
https://auth0.com/docs/quickstart/native-mobile/cordova/no-api
https://auth0.com/docs/quickstart/native-mobile/cordova/wcf-service
https://auth0.com/docs/quickstart/native-mobile/cordova/aspnet-webapi
https://auth0.com/docs/quickstart/native-mobile/cordova/webapi-owin
https://auth0.com/docs/quickstart/native-mobile/cordova/aws
https://auth0.com/docs/quickstart/native-mobile/cordova/azure-blob-storage
https://auth0.com/docs/quickstart/native-mobile/cordova/azure-mobile-services
https://auth0.com/docs/quickstart/native-mobile/cordova/azure-sb
https://auth0.com/docs/quickstart/native-mobile/cordova/firebase
https://auth0.com/docs/quickstart/native-mobile/cordova/golang
https://auth0.com/docs/quickstart/native-mobile/cordova/java
https://auth0.com/docs/quickstart/native-mobile/cordova/nodejs
https://auth0.com/docs/quickstart/native-mobile/cordova/php-laravel
https://auth0.com/docs/quickstart/native-mobile/cordova/php-symfony
https://auth0.com/docs/quickstart/native-mobile/cordova/php
https://auth0.com/docs/quickstart/native-mobile/cordova/python
https://auth0.com/docs/quickstart/native-mobile/cordova/ruby
https://auth0.com/docs/quickstart/native-mobile/cordova/rails
https://auth0.com/docs/quickstart/native-mobile/cordova/salesforce
https://auth0.com/docs/quickstart/native-mobile/cordova/salesforce-sandbox
https://auth0.com/docs/quickstart/native-mobile/cordova/sap-odata
https://auth0.com/docs/quickstart/native-mobile/cordova/java-spring-security
https://auth0.com/docs/quickstart/native-mobile/ionic
https://auth0.com/docs/quickstart/native-mobile/ionic/no-api
https://auth0.com/docs/quickstart/native-mobile/ionic/wcf-service
https://auth0.com/docs/quickstart/native-mobile/ionic/aspnet-webapi
https://auth0.com/docs/quickstart/native-mobile/ionic/webapi-owin
https://auth0.com/docs/quickstart/native-mobile/ionic/aws
https://auth0.com/docs/quickstart/native-mobile/ionic/azure-blob-storage
https://auth0.com/docs/quickstart/native-mobile/ionic/azure-mobile-services
https://auth0.com/docs/quickstart/native-mobile/ionic/azure-sb
https://auth0.com/docs/quickstart/native-mobile/ionic/firebase
https://auth0.com/docs/quickstart/native-mobile/ionic/golang
https://auth0.com/docs/quickstart/native-mobile/ionic/java
https://auth0.com/docs/quickstart/native-mobile/ionic/nodejs
https://auth0.com/docs/quickstart/native-mobile/ionic/php-laravel
https://auth0.com/docs/quickstart/native-mobile/ionic/php-symfony
https://auth0.com/docs/quickstart/native-mobile/ionic/php
https://auth0.com/docs/quickstart/native-mobile/ionic/python
https://auth0.com/docs/quickstart/native-mobile/ionic/ruby
https://auth0.com/docs/quickstart/native-mobile/ionic/rails
https://auth0.com/docs/quickstart/native-mobile/ionic/salesforce
https://auth0.com/docs/quickstart/native-mobile/ionic/salesforce-sandbox
https://auth0.com/docs/quickstart/native-mobile/ionic/sap-odata
https://auth0.com/docs/quickstart/native-mobile/ionic/java-spring-security
https://auth0.com/docs/quickstart/native-mobile/ios-objc/firebase
https://auth0.com/docs/quickstart/native-mobile/ios-objc/sap-odata
https://auth0.com/docs/quickstart/native-mobile/ios-reactnative
https://auth0.com/docs/quickstart/native-mobile/ios-reactnative/no-api
https://auth0.com/docs/quickstart/native-mobile/ios-reactnative/wcf-service
https://auth0.com/docs/quickstart/native-mobile/ios-reactnative/aspnet-webapi
https://auth0.com/docs/quickstart/native-mobile/ios-reactnative/webapi-owin
https://auth0.com/docs/quickstart/native-mobile/ios-reactnative/aws
https://auth0.com/docs/quickstart/native-mobile/ios-reactnative/azure-blob-storage
https://auth0.com/docs/quickstart/native-mobile/ios-reactnative/azure-mobile-services
https://auth0.com/docs/quickstart/native-mobile/ios-reactnative/azure-sb
https://auth0.com/docs/quickstart/native-mobile/ios-reactnative/firebase
https://auth0.com/docs/quickstart/native-mobile/ios-reactnative/golang
https://auth0.com/docs/quickstart/native-mobile/ios-reactnative/java
https://auth0.com/docs/quickstart/native-mobile/ios-reactnative/nodejs
https://auth0.com/docs/quickstart/native-mobile/ios-reactnative/php-laravel
https://auth0.com/docs/quickstart/native-mobile/ios-reactnative/php-symfony
https://auth0.com/docs/quickstart/native-mobile/ios-reactnative/python
https://auth0.com/docs/quickstart/native-mobile/ios-reactnative/ruby
https://auth0.com/docs/quickstart/native-mobile/ios-reactnative/rails
https://auth0.com/docs/quickstart/native-mobile/ios-reactnative/salesforce
https://auth0.com/docs/quickstart/native-mobile/ios-reactnative/salesforce-sandbox
https://auth0.com/docs/quickstart/native-mobile/ios-reactnative/sap-odata
https://auth0.com/docs/quickstart/native-mobile/ios-reactnative/java-spring-security
https://auth0.com/docs/quickstart/native-mobile/phonegap
https://auth0.com/docs/quickstart/native-mobile/phonegap/wcf-service
https://auth0.com/docs/quickstart/native-mobile/phonegap/aspnet-webapi
https://auth0.com/docs/quickstart/native-mobile/phonegap/webapi-owin
https://auth0.com/docs/quickstart/native-mobile/phonegap/aws
https://auth0.com/docs/quickstart/native-mobile/phonegap/azure-blob-storage
https://auth0.com/docs/quickstart/native-mobile/phonegap/azure-mobile-services
https://auth0.com/docs/quickstart/native-mobile/phonegap/azure-sb
https://auth0.com/docs/quickstart/native-mobile/phonegap/firebase
https://auth0.com/docs/quickstart/native-mobile/phonegap/golang
https://auth0.com/docs/quickstart/native-mobile/phonegap/java
https://auth0.com/docs/quickstart/native-mobile/phonegap/nodejs
https://auth0.com/docs/quickstart/native-mobile/phonegap/php-laravel
https://auth0.com/docs/quickstart/native-mobile/phonegap/php-symfony
https://auth0.com/docs/quickstart/native-mobile/phonegap/php
https://auth0.com/docs/quickstart/native-mobile/phonegap/python
https://auth0.com/docs/quickstart/native-mobile/phonegap/ruby
https://auth0.com/docs/quickstart/native-mobile/phonegap/rails
https://auth0.com/docs/quickstart/native-mobile/phonegap/salesforce
https://auth0.com/docs/quickstart/native-mobile/phonegap/salesforce-sandbox
https://auth0.com/docs/quickstart/native-mobile/phonegap/sap-odata
https://auth0.com/docs/quickstart/native-mobile/phonegap/java-spring-security
https://auth0.com/docs/quickstart/native-mobile/windowsphone
https://auth0.com/docs/quickstart/native-mobile/windows-store-csharp
https://auth0.com/docs/quickstart/native-mobile/windows-store-csharp/firebase
https://auth0.com/docs/quickstart/native-mobile/windows-store-csharp/sap-odata
https://auth0.com/docs/quickstart/native-mobile/windows-store-javascript
https://auth0.com/docs/quickstart/native-mobile/windows-store-javascript/firebase
https://auth0.com/docs/quickstart/native-mobile/windows-store-javascript/sap-odata
https://auth0.com/docs/quickstart/native-mobile/wpf-winforms
https://auth0.com/docs/quickstart/native-mobile/xamarin
https://auth0.com/docs/quickstart/native-mobile/xamarin/firebase
https://auth0.com/docs/quickstart/native-mobile/xamarin/sap-odata
https://auth0.com/docs/quickstart/spa
https://auth0.com/docs/quickstart/spa/angularjs
https://auth0.com/docs/quickstart/spa/emberjs/azure-blob-storage
https://auth0.com/docs/quickstart/spa/emberjs/azure-sb
https://auth0.com/docs/quickstart/spa/jquery
https://auth0.com/docs/quickstart/spa/react/azure-sb
https://auth0.com/docs/quickstart/spa/react/firebase
https://auth0.com/docs/quickstart/webapp
https://auth0.com/docs/quickstart/hybrid
https://auth0.com/docs/quickstart/hybrid/cordova
https://auth0.com/docs/quickstart/hybrid/cordova/no-api
https://auth0.com/docs/quickstart/hybrid/cordova/wcf-service
https://auth0.com/docs/quickstart/hybrid/cordova/aspnet-webapi
https://auth0.com/docs/quickstart/hybrid/cordova/webapi-owin
https://auth0.com/docs/quickstart/hybrid/cordova/aws
https://auth0.com/docs/quickstart/hybrid/cordova/azure-blob-storage
https://auth0.com/docs/quickstart/hybrid/cordova/azure-mobile-services
https://auth0.com/docs/quickstart/hybrid/cordova/azure-sb
https://auth0.com/docs/quickstart/hybrid/cordova/firebase
https://auth0.com/docs/quickstart/hybrid/cordova/golang
https://auth0.com/docs/quickstart/hybrid/cordova/java
https://auth0.com/docs/quickstart/hybrid/cordova/nodejs
https://auth0.com/docs/quickstart/hybrid/cordova/php-laravel
https://auth0.com/docs/quickstart/hybrid/cordova/php-symfony
https://auth0.com/docs/quickstart/hybrid/cordova/php
https://auth0.com/docs/quickstart/hybrid/cordova/python
https://auth0.com/docs/quickstart/hybrid/cordova/ruby
https://auth0.com/docs/quickstart/hybrid/cordova/rails
https://auth0.com/docs/quickstart/hybrid/cordova/salesforce
https://auth0.com/docs/quickstart/hybrid/cordova/salesforce-sandbox
https://auth0.com/docs/quickstart/hybrid/cordova/sap-odata
https://auth0.com/docs/quickstart/hybrid/cordova/java-spring-security
https://auth0.com/docs/quickstart/hybrid/ionic
https://auth0.com/docs/quickstart/hybrid/ionic/no-api
https://auth0.com/docs/quickstart/hybrid/ionic/wcf-service
https://auth0.com/docs/quickstart/hybrid/ionic/aspnet-webapi
https://auth0.com/docs/quickstart/hybrid/ionic/webapi-owin
https://auth0.com/docs/quickstart/hybrid/ionic/aws
https://auth0.com/docs/quickstart/hybrid/ionic/azure-blob-storage
https://auth0.com/docs/quickstart/hybrid/ionic/azure-mobile-services
https://auth0.com/docs/quickstart/hybrid/ionic/azure-sb
https://auth0.com/docs/quickstart/hybrid/ionic/firebase
https://auth0.com/docs/quickstart/hybrid/ionic/golang
https://auth0.com/docs/quickstart/hybrid/ionic/java
https://auth0.com/docs/quickstart/hybrid/ionic/nodejs
https://auth0.com/docs/quickstart/hybrid/ionic/php-laravel
https://auth0.com/docs/quickstart/hybrid/ionic/php-symfony
https://auth0.com/docs/quickstart/hybrid/ionic/php
https://auth0.com/docs/quickstart/hybrid/ionic/python
https://auth0.com/docs/quickstart/hybrid/ionic/ruby
https://auth0.com/docs/quickstart/hybrid/ionic/rails
https://auth0.com/docs/quickstart/hybrid/ionic/salesforce
https://auth0.com/docs/quickstart/hybrid/ionic/salesforce-sandbox
https://auth0.com/docs/quickstart/hybrid/ionic/sap-odata
https://auth0.com/docs/quickstart/hybrid/ionic/java-spring-security
https://auth0.com/docs/quickstart/hybrid/ios-reactnative
https://auth0.com/docs/quickstart/hybrid/ios-reactnative/no-api
https://auth0.com/docs/quickstart/hybrid/ios-reactnative/wcf-service
https://auth0.com/docs/quickstart/hybrid/ios-reactnative/aspnet-webapi
https://auth0.com/docs/quickstart/hybrid/ios-reactnative/webapi-owin
https://auth0.com/docs/quickstart/hybrid/ios-reactnative/aws
https://auth0.com/docs/quickstart/hybrid/ios-reactnative/azure-blob-storage
https://auth0.com/docs/quickstart/hybrid/ios-reactnative/azure-mobile-services
https://auth0.com/docs/quickstart/hybrid/ios-reactnative/azure-sb
https://auth0.com/docs/quickstart/hybrid/ios-reactnative/firebase
https://auth0.com/docs/quickstart/hybrid/ios-reactnative/golang
https://auth0.com/docs/quickstart/hybrid/ios-reactnative/java
https://auth0.com/docs/quickstart/hybrid/ios-reactnative/nodejs
https://auth0.com/docs/quickstart/hybrid/ios-reactnative/php-laravel
https://auth0.com/docs/quickstart/hybrid/ios-reactnative/php-symfony
https://auth0.com/docs/quickstart/hybrid/ios-reactnative/python
https://auth0.com/docs/quickstart/hybrid/ios-reactnative/ruby
https://auth0.com/docs/quickstart/hybrid/ios-reactnative/rails
https://auth0.com/docs/quickstart/hybrid/ios-reactnative/salesforce
https://auth0.com/docs/quickstart/hybrid/ios-reactnative/salesforce-sandbox
https://auth0.com/docs/quickstart/hybrid/ios-reactnative/sap-odata
https://auth0.com/docs/quickstart/hybrid/ios-reactnative/java-spring-security
https://auth0.com/docs/quickstart/hybrid/phonegap
https://auth0.com/docs/quickstart/hybrid/phonegap/wcf-service
https://auth0.com/docs/quickstart/hybrid/phonegap/aspnet-webapi
https://auth0.com/docs/quickstart/hybrid/phonegap/webapi-owin
https://auth0.com/docs/quickstart/hybrid/phonegap/aws
https://auth0.com/docs/quickstart/hybrid/phonegap/azure-blob-storage
https://auth0.com/docs/quickstart/hybrid/phonegap/azure-mobile-services
https://auth0.com/docs/quickstart/hybrid/phonegap/azure-sb
https://auth0.com/docs/quickstart/hybrid/phonegap/firebase
https://auth0.com/docs/quickstart/hybrid/phonegap/golang
https://auth0.com/docs/quickstart/hybrid/phonegap/java
https://auth0.com/docs/quickstart/hybrid/phonegap/nodejs
https://auth0.com/docs/quickstart/hybrid/phonegap/php-laravel
https://auth0.com/docs/quickstart/hybrid/phonegap/php-symfony
https://auth0.com/docs/quickstart/hybrid/phonegap/php
https://auth0.com/docs/quickstart/hybrid/phonegap/python
https://auth0.com/docs/quickstart/hybrid/phonegap/ruby
https://auth0.com/docs/quickstart/hybrid/phonegap/rails
https://auth0.com/docs/quickstart/hybrid/phonegap/salesforce
https://auth0.com/docs/quickstart/hybrid/phonegap/salesforce-sandbox
https://auth0.com/docs/quickstart/hybrid/phonegap/sap-odata
https://auth0.com/docs/quickstart/hybrid/phonegap/java-spring-security

More info -> https://docs.google.com/a/auth10.com/spreadsheets/d/1O0aZlORVTLTtUPeXeceiEIgClZuvAOwrcm64_28gy2s/edit?usp=sharing

**Comment by ntotten** [comment] 2015-09-08 19:11
Is this the duplicate title issue? They shouldn't have duplicate content.

**Comment by plaurino** [comment] 2015-09-08 19:17
Sorry, the only problem here is the missed description. Working with @tehsis on this now.

**Comment by ntotten** [comment] 2015-11-10 20:10
@Catografix All of these pages need a meta description property on them at the top of the document.

```
---
description: this is an article
---
```

**Comment by iannyanes** [comment] 2015-11-10 21:55
According to @Annyv2  All the Meta descriptions are there. Can you Check again and leave a comment anny?

**Comment by Annyv2** [comment] 2015-11-10 22:02
All the websites were checked and they have the types of descriptions described here https://moz.com/learn/seo/meta-description. For example

![metadescription2](https://cloud.githubusercontent.com/assets/5016479/11077246/480a1558-87d1-11e5-9120-603c6dd0efc4.JPG)

**Comment by ntotten** [comment] 2015-11-11 21:30
@iannyanes @Annyv2 Don't worry about this ticket, it is assigned to @Catografix. The issue is that they need unique descriptions.

**Comment by Catografix** [comment] 2015-11-18 03:56
@ntotten These seem to be ok.
Ive manually checked the first 30 docs and a few others by viewing their source. They all have unique descriptions except for the 2nd to the 8th - which are blank or 404 docs.

[descriptions.xlsx](https://github.com/auth0/docs/files/37491/descriptions.xlsx)

I can continue the manual check of all 211 if desired.

**Closed as completed** 2016-01-08 02:53 UTC
Labels: update-needed
