### ISSUE TITLE
Laravel Webapp doc: Outdated dependency in System requirements.

### ISSUE THREAD

**Issue by paulioceano** [auth0/docs#6477] opened 2018-08-02 18:59 UTC
In the [Laravel docs](https://auth0.com/docs/quickstart/webapp/laravel), the System requirement sections indicates that PHP 7.0 is needed:

![screenshot_2](https://user-images.githubusercontent.com/15818783/43604340-85596686-9663-11e8-9435-df87ce400bb9.png)

But, when runing composer install with PHP v 7.0.23, it fails and indicate that PHP v. 7.1 is needed:

![screenshot_1](https://user-images.githubusercontent.com/15818783/43604791-a871d1d4-9664-11e8-8013-e7e5e5983c9e.png)

**Comment by joshcanhelp** [comment] 2018-08-06 15:46
@paulioceano - Thanks for the report here. I was just bit by this in another library and I think one of the common Composer requirements we use might have updated and is causing this. We'll take a look at this as soon as we can.

**Comment by albertoperdomo** [comment] 2018-08-08 14:44
Would updating the system reqs to 7.1 a good fix for this @joshcanhelp ?
If so, happy to do that myself.

**Comment by joshcanhelp** [comment] 2018-08-08 14:49
@albertoperdomo - Laravel 5.5 (which we require) only requires 7.0, I wouldn't go any higher than that. I think we need to figure out where this dependency is coming from. 

We do probably want to upgrade auth0-PHP to `~5.2.0` through:

https://github.com/auth0-samples/auth0-laravel-php-web-app/blob/master/00-Starter-Seed/composer.json#L10

Are you able to reproduce on your end?

**Comment by albertoperdomo** [comment] 2018-08-08 14:54
Thanks for the clarification @joshcanhelp!

So if I understood correctly, the problem is not actually that we are documenting the wrong dependency version. It's that we have seemed to have accidentally bumped the version to a higher version than actually required.

I'm on Mac and have already PHP 7.1. Is there a way I could reproduce this easily?
I don't have much background with PHP but should be able to reproduce if I can get a clean environment to begin with.

**Closed as completed** 2019-10-15 13:14 UTC
Labels: update-needed, quickstart, verified
